<?php

/**
 * maklermodul for Contao Open Source CMS
 *
 * Copyright (C) 2017 pdir / digital agentur <develop@pdir.de>
 *
 * @package    maklermodul
 * @link       https://www.maklermodul.de
 * @license    pdir license - All-rights-reserved - commercial extension
 * @author     pdir GmbH <develop@pdir.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * Namespace
 */
namespace Pdir\MaklermodulBundle\Maklermodul\FieldRenderer;

use Pdir\MaklermodulBundle\Maklermodul\Domain\Model\Estate;
use Pdir\MaklermodulBundle\Maklermodul\FieldRenderer;
use Pdir\MaklermodulBundle\Maklermodul\FieldTranslator;

class Date extends FieldRenderer
{
    const DEFAULT_INPUT_FORMAT = 'Y-m-d';
    const DEFAULT_OUTPUT_FORMAT = 'd.m.Y';

    public function __construct($key, $value, FieldTranslator $translator)
    {
        $value = \DateTime::createFromFormat(self::DEFAULT_INPUT_FORMAT, $value);

        parent::__construct(
            $key,
            $value,
            $translator
        ); // @todo: Change the autogenerated stub
    }

    /**
     * Methode für Rückgabe eines Wertes.
     *
     * Der Wert wird so dargestellt, wie er in der Objektbeschreibung steht.
     *
     * @param bool $doNotPrint
     * @return string
     */
    public function value($doNotPrint = false)
    {
        $returnValue = $this->getSetting('prefix');

        if (is_a($this->getValue(), '\DateTime')) {
            $returnValue .= $this->getValue()->format(self::DEFAULT_OUTPUT_FORMAT);
        }

        $returnValue .= $this->getSetting('append');

        return $returnValue;
    }

    /**
     * Rückgabe des Wertes als Text.
     *
     * @return string
     */
    public function __toString()
    {
        if ($this->getSetting('withoutLabel')) {
            $template = $this->getShortTemplate();
            return sprintf(
                $template,
                Estate::sanizeFileName($this->getKey()),
                $this->value(true)
            );
        }

        $template = $this->getLongTempalte();
        return sprintf(
            $template,
            Estate::sanizeFileName($this->getKey()),
            $this->key(true),
            $this->value(true)
        );
    }

    private function getLongTempalte()
    {
        return <<<EOT
<div class="field %s">
    <div class="label">%s</div>
    <div class="value-date">%s</div>
</div>
EOT;
    }

    private function getShortTemplate()
    {
        return <<<EOT
<div class="field %s value-date">%s</div>
EOT;
    }
}
