services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - [setFramework, ['@contao.framework']]

    pdir_maklermodul.listener.data_container:
        class: Pdir\MaklermodulBundle\EventListener\DataContainerListener
        public: true
